import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";

import GlobalStyle from "./globalStyle";
import { ThemeProvider } from "@/theme/theme";
import StyledComponentsRegistry from "@/lib/styledComponentsRegistry";

const inter = Inter({ subsets: ["latin"], variable: "--inter" });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"],
  variable: "--poppins",
});

export const metadata: Metadata = {
  title: "University Of Snacks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${inter.variable} ${poppins.variable}`}>
        <StyledComponentsRegistry>
          <ThemeProvider>
            <GlobalStyle />
            {children}
          </ThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
